### ISSUE TITLE
大佬 有时间能写idea插件吗 

### ISSUE THREAD

**Issue by shuigedeng** [camilesing/Flink-SQL-Helper-VSCode#11]

**Comment by camilesing** [comment]
Developing the plugin for Idea is not that simple, I need some time to develop it. But I don't have enough time now to do this..

> 开发idea的插件需要一些时间，因为它不是很简单。但是我现在没有充足的资源来做这件事。。

**Comment by camilesing** [comment]
@shuigedeng plugin for IDEA version has been released. see: https://plugins.jetbrains.com/plugin/25912-flink-sql-helper

> IDEA版本的FlinkSQL Helper已经发版，详情见：https://plugins.jetbrains.com/plugin/25912-flink-sql-helper
